### ISSUE TITLE
Render.py: unexpected keyword argument 'fps'

### ISSUE THREAD

**Issue by Tao-11-chen** [SuLvXiangXin/zipnerf-pytorch#19]
Hello, thanks for your excellent work, I got this issue while rendering my video:

Making video exp/***/**_exp_path_renders_step_25000_color.mp4...
Traceback (most recent call last):
  File "/home/****/zipnerf-pytorch/render.py", line 163, in <module>
    app.run(main)
  File "/home/****/.conda/envs/zipnerf/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/****/.conda/envs/zipnerf/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/****/zipnerf-pytorch/render.py", line 157, in main
    create_videos(config, config.render_dir, out_dir, out_name, dataset.size)
  File "/home/****/zipnerf-pytorch/render.py", line 74, in create_videos
    writer.append_data(frame)
  File "/home/****/.conda/envs/zipnerf/lib/python3.9/site-packages/imageio/v2.py", line 215, in append_data
    return self.instance.write(im, **self.write_args)
  File "/home/****/.conda/envs/zipnerf/lib/python3.9/site-packages/imageio/plugins/tifffile_v3.py", line 244, in write
    self._fh.write(image, **kwargs)
TypeError: write() got an unexpected keyword argument 'fps'

**Comment by SuLvXiangXin** [comment]
@Tao-11-chen Perhaps it is due to the version you have. Try `pip install -U imageio`, or check the latest commit.

**Comment by ZhangWeiSYSU** [comment]
@Tao-11-chen  You can try:
`pip install imageio[ffmpeg] imageio[pyav]` 

This is helpful for me to tackle the "fps" problem.

**Comment by Tao-11-chen** [comment]
@ZhangWeiSYSU @SuLvXiangXin Problem solved, thx.

**Comment by ZhangWeiSYSU** [comment]
您好，您的来信已收到，我会尽快给您回复。
