### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'exp/360_v2/bicycle/checkpoints/025000/scaler.pt'

### ISSUE THREAD

**Issue by IMath123** [SuLvXiangXin/zipnerf-pytorch#23]
I trained and got:
[...]
2023-05-26 18:17:06:  24900/25000: loss=0.03918, psnr=23.821, lr=1.01e-03 | data=0.03578, anti=7.3e-05, dist=0.00016, hash=0.00317, 51921 r/s
2023-05-26 18:17:22:  25000/25000: loss=0.03925, psnr=23.803, lr=1.00e-03 | data=0.03585, anti=7.4e-05, dist=0.00016, hash=0.00316, 51515 r/s
2023-05-26 18:17:22: Saving current state to exp/360_v2/bicycle/checkpoints/025000                                                      
2023-05-26 18:17:23: Model weights saved in exp/360_v2/bicycle/checkpoints/025000/pytorch_model.bin                                     
2023-05-26 18:17:24: Optimizer state saved in exp/360_v2/bicycle/checkpoints/025000/optimizer.bin                                       
2023-05-26 18:17:24: Random states saved in exp/360_v2/bicycle/checkpoints/025000/random_states_0.pkl                                   
2023-05-26 18:17:46: Eval 25000: 22.273s, 45653 rays/sec                                                                                
2023-05-26 18:17:46: Metrics computed in 0.086s                                                                                         
2023-05-26 18:17:46: psnr = 25.3830                                                                                                     
2023-05-26 18:17:46: ssim = 0.7320                                                                                                      
2023-05-26 18:17:46: Visualized in 0.233s                                                                                               
Training: 25001it [1:27:45,  4.75it/s]                                                                                                  
2023-05-26 18:17:49: Saving last checkpoint at step 25000 to exp/360_v2/bicycle/checkpoints
2023-05-26 18:17:49: Saving current state to exp/360_v2/bicycle/checkpoints/025000
2023-05-26 18:17:50: Model weights saved in exp/360_v2/bicycle/checkpoints/025000/pytorch_model.bin
2023-05-26 18:17:51: Optimizer state saved in exp/360_v2/bicycle/checkpoints/025000/optimizer.bin
2023-05-26 18:17:51: Random states saved in exp/360_v2/bicycle/checkpoints/025000/random_states_0.pkl
2023-05-26 18:17:51: Finish training.

then I run eval.py, got this:
[...]
Warning: image_path not found for reconstruction
2023-05-26 19:09:34: Resuming from checkpoint exp/360_v2/bicycle/checkpoints/025000                                                     
2023-05-26 19:09:34: Loading states from exp/360_v2/bicycle/checkpoints/025000
2023-05-26 19:09:34: All model weights loaded successfully
2023-05-26 19:09:34: All optimizer states loaded successfully
2023-05-26 19:09:34: All scheduler states loaded successfully
2023-05-26 19:09:34: Error!
Traceback (most recent call last):
  File "/home/omnispace/Projects/zipnerf-pytorch/eval.py", line 307, in <module>
    app.run(main)
  File "/home/omnispace/anaconda3/envs/zipnerf/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/omnispace/anaconda3/envs/zipnerf/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/omnispace/Projects/zipnerf-pytorch/eval.py", line 115, in main
    step = checkpoints.restore_checkpoint(config.checkpoint_dir, accelerator, logger)
  File "/home/omnispace/Projects/zipnerf-pytorch/internal/checkpoints.py", line 24, in restore_checkpoint
    accelerator.load_state(path)
  File "/home/omnispace/anaconda3/envs/zipnerf/lib/python3.9/site-packages/accelerate/accelerator.py", line 2466, in load_state
    load_accelerator_state(
  File "/home/omnispace/anaconda3/envs/zipnerf/lib/python3.9/site-packages/accelerate/checkpointing.py", line 177, in load_accelerator_state
    scaler.load_state_dict(torch.load(input_scaler_file))
  File "/home/omnispace/anaconda3/envs/zipnerf/lib/python3.9/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/omnispace/anaconda3/envs/zipnerf/lib/python3.9/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/omnispace/anaconda3/envs/zipnerf/lib/python3.9/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'exp/360_v2/bicycle/checkpoints/025000/scaler.pt'

**Comment by SuLvXiangXin** [comment]
@IMath123 Maybe that is because you use different configuration for in `accelerate config`, train without fp16 and eval with fp16, I guess.

**Comment by IMath123** [comment]
<img width="354" alt="image" src="https://github.com/SuLvXiangXin/zipnerf-pytorch/assets/39054181/64f7816c-a866-44ef-9147-8682dbfb0a66">
<img width="358" alt="image" src="https://github.com/SuLvXiangXin/zipnerf-pytorch/assets/39054181/27eacb57-b1f2-4706-8d82-e5a6c98d76dd">
I run it without "accelerate config".

**Comment by SuLvXiangXin** [comment]
Sorry, it's my fault, you can delete the selected code in the photo, then it may work.
<img width="959" alt="image" src="https://github.com/SuLvXiangXin/zipnerf-pytorch/assets/83005605/ec593256-c027-48c0-93b2-4c11856f8e88">

**Comment by IMath123** [comment]
Thanks!!! It works now!

**Comment by hg111** [comment]
@SuLvXiangXin  Hi! I have the same error, but in my case render.py doesn't have accelerator = accelerate.Accelerator('mixed_precision'='fp16'), and only  accelerator = accelerate.Accelerator, yet I get the same error. (I also used 'python train.py...' . It appears that it picked up the 'fp16' from the accelerate configeven i didn't use 'accelerate launch train.py'...)  What to do? I rather not re-train if don't have to, since it takes couple of days..

**Comment by hg111** [comment]
as it turned out out just deleting the 'fp16' line in default_config.yaml solved the problem
