### ISSUE TITLE
Extracting Mesh raises an OutOfMemoryError

### ISSUE THREAD

**Issue by Systho** [SuLvXiangXin/zipnerf-pytorch#33]
First of all, big thanks for your work, it's awesome. And even more thanks for actually taking the time of addressing issues !

As the title suggests, I get an OutOfMemoryError when extracting Mesh.
I have a "small" machine (Laptop with RTX2080Super, 8giB video memory, 32giB RAM)

The crashes happens after (or during) the computation of density map.

Here is the log :

```
accelerate launch extract.py --gin_configs=configs/360.gin \                                                                                       [15:59:48]
  --gin_bindings="Config.data_dir = '${DATA_DIR}'" \
  --gin_bindings="Config.exp_name = '${EXP_NAME}'" \
  --gin_bindings="Config.factor = 4" \
  --gin_bindings="Config.batch_size = 4096" \
  --gin_bindings="Config.render_chunk_size = 4096"

I0608 15:59:50.251319 139980354081152 logging.py:47] Config(dataset_loader='llff', batching='all_images', batch_size=4096, patch_size=1, factor=4, multiscale=False, multiscale_levels=4, forward_facing=False, render_path=False, llffhold=8, llff_use_all_images_for_training=False, llff_use_all_images_for_testing=False, use_tiffs=False, compute_disp_metrics=False, compute_normal_metrics=False, disable_multiscale_loss=False, randomized=True, near=0.2, far=1000000.0, exp_name='chill_room_113', data_dir='data/chill_room_113', vocab_tree_path=None, render_chunk_size=4096, num_showcase_images=5, deterministic_showcase=True, vis_num_rays=16, vis_decimate=0, max_steps=25000, early_exit_steps=None, checkpoint_every=5000, resume_from_checkpoint=True, checkpoints_total_limit=1, print_every=100, train_render_every=500, data_loss_type='charb', charb_padding=0.001, data_loss_mult=1.0, data_coarse_loss_mult=0.0, interlevel_loss_mult=0.0, anti_interlevel_loss_mult=0.01, orientation_loss_mult=0.0, orientation_coarse_loss_mult=0.0, orientation_loss_target='normals_pred', predicted_normal_loss_mult=0.0, predicted_normal_coarse_loss_mult=0.0, hash_decay_mults=0.1, lr_init=0.01, lr_final=0.001, lr_delay_steps=5000, lr_delay_mult=1e-08, adam_beta1=0.9, adam_beta2=0.99, adam_eps=1e-15, grad_max_norm=0.0, grad_max_val=0.0, distortion_loss_mult=0.005, opacity_loss_mult=0.0, eval_only_once=True, eval_save_output=True, eval_save_ray_data=False, eval_render_interval=1, eval_dataset_limit=2147483647, eval_quantize_metrics=True, eval_crop_borders=0, render_video_fps=60, render_video_crf=18, render_path_frames=120, z_variation=0.0, z_phase=0.0, render_dist_percentile=0.5, render_dist_curve_fn=<ufunc 'log'>, render_path_file=None, render_resolution=None, render_focal=None, render_camtype=None, render_spherical=False, render_save_async=True, render_spline_keyframes=None, render_spline_n_interp=30, render_spline_degree=5, render_spline_smoothness=0.03, render_spline_interpolate_exposure=False, rawnerf_mode=False, exposure_percentile=97.0, num_border_pixels_to_mask=0, apply_bayer_mask=False, autoexpose_renders=False, eval_raw_affine_cc=False, zero_glo=False, valid_weight_thresh=0.05, isosurface_threshold=20, mesh_voxels=134217728, visibility_resolution=512, mesh_radius=1.0, mesh_max_radius=10.0, std_value=0.0, compute_visibility=True, extract_visibility=True, decimate_target=-1, vertex_color=True, vertex_projection=True)
I0608 15:59:50.251490 139980354081152 logging.py:47] Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no

I0608 15:59:51.605862 139980354081152 logging.py:47] Resuming from checkpoint exp/chill_room_113/checkpoints/025000
I0608 15:59:51.606026 139980354081152 logging.py:47] Loading states from exp/chill_room_113/checkpoints/025000
I0608 15:59:51.874377 139980354081152 logging.py:47] All model weights loaded successfully
I0608 15:59:51.874529 139980354081152 logging.py:47] All optimizer states loaded successfully
I0608 15:59:51.874603 139980354081152 logging.py:47] All scheduler states loaded successfully
I0608 15:59:51.875286 139980354081152 logging.py:47] All random states loaded successfully
I0608 15:59:51.875415 139980354081152 logging.py:47] Loading in 0 custom states
I0608 15:59:51.875766 139980354081152 logging.py:47] Generate visibility mask...
Generating visibility grid: 100%|████████████████████████████████████████████████████████████████████████| 98/98 [05:07<00:00,  3.13s/it, visibility_mask=0.0363]
I0608 16:04:59.862720 139980354081152 logging.py:47] Extract mesh from visibility mask...
I0608 16:05:06.356143 139980354081152 logging.py:47] Extract visibility mask done.
I0608 16:05:06.505425 139980354081152 logging.py:47] Process grid cell (1/1, 1/1, 1/1)...
E0608 16:05:22.405724 139980354081152 utils.py:40] Error!                                                                                                        
Traceback (most recent call last):
  File "extract.py", line 638, in <module>
    app.run(main)
  File "/home/pve/.pyenv/versions/3.7.2/lib/python3.7/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/pve/.pyenv/versions/3.7.2/lib/python3.7/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "extract.py", line 431, in main
    points_world = coord.inv_contract(2 * points)
  File "/home/pve/Projects/zipnerf-pytorch/internal/coord.py", line 23, in inv_contract
    z_mag_sq = torch.sum(z ** 2, dim=-1, keepdim=True).clamp_min(eps)
  File "/home/pve/.pyenv/versions/3.7.2/lib/python3.7/site-packages/torch/_tensor.py", line 39, in wrapped
    return f(*args, **kwargs)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.50 GiB (GPU 0; 7.78 GiB total capacity; 4.60 GiB already allocated; 420.19 MiB free; 5.71 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/home/pve/.pyenv/versions/3.7.2/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/pve/.pyenv/versions/3.7.2/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/pve/.pyenv/versions/3.7.2/lib/python3.7/site-packages/accelerate/commands/launch.py", line 918, in launch_command
    simple_launcher(args)
  File "/home/pve/.pyenv/versions/3.7.2/lib/python3.7/site-packages/accelerate/commands/launch.py", line 580, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/pve/.pyenv/versions/3.7.2/bin/python3.7', 'extract.py', '--gin_configs=configs/360.gin', "--gin_bindings=Config.data_dir = 'data/chill_room_113'", "--gin_bindings=Config.exp_name = 'chill_room_113'", '--gin_bindings=Config.factor = 4', '--gin_bindings=Config.batch_size = 4096', '--gin_bindings=Config.render_chunk_size = 4096']' returned non-zero exit status 1.
>>> elapsed time 5m34s
```

Tuning batch_size and render_chink_size lower (down to 1024) has no effect.

**Comment by SuLvXiangXin** [comment]
@Systho Maybe turn mesh_voxels lower can help, e.g.  1000000, which is 100**3.

**Comment by ldzhuang** [comment]
Have you successfully run it？

**Comment by SuLvXiangXin** [comment]
Of course, you can see the photo of mesh in readme

**Comment by Systho** [comment]
Yes, it's working, thank you so much !
