### ISSUE TITLE
multi360 rendering : IndexError: index 15 is out of bounds for axis 0 with size 15

### ISSUE THREAD

**Issue by Systho** [SuLvXiangXin/zipnerf-pytorch#38]
I managed to train an model using multi360 config but then when I try to render a video I get this error, any idea how to fix it ? 

```
 ❯ bash scripts/render_360.sh                                        [14:12:36]
I0612 14:12:39.029760 139869331714432 logging.py:47] Config(dataset_loader='llff', batching='all_images', batch_size=6000, patch_size=1, factor=2, multiscale=True, multiscale_levels=4, forward_facing=False, render_path=True, llffhold=8, llff_use_all_images_for_training=False, llff_use_all_images_for_testing=False, use_tiffs=False, compute_disp_metrics=False, compute_normal_metrics=False, disable_multiscale_loss=False, randomized=True, near=0.2, far=1000000.0, exp_name='chill_room_113_multi360', data_dir='data/chill_room_113', vocab_tree_path=None, render_chunk_size=6000, num_showcase_images=5, deterministic_showcase=True, vis_num_rays=16, vis_decimate=0, max_steps=25000, early_exit_steps=None, checkpoint_every=5000, resume_from_checkpoint=True, checkpoints_total_limit=1, print_every=100, train_render_every=500, data_loss_type='charb', charb_padding=0.001, data_loss_mult=1.0, data_coarse_loss_mult=0.0, interlevel_loss_mult=0.0, anti_interlevel_loss_mult=0.01, orientation_loss_mult=0.0, orientation_coarse_loss_mult=0.0, orientation_loss_target='normals_pred', predicted_normal_loss_mult=0.0, predicted_normal_coarse_loss_mult=0.0, hash_decay_mults=0.1, lr_init=0.01, lr_final=0.001, lr_delay_steps=5000, lr_delay_mult=1e-08, adam_beta1=0.9, adam_beta2=0.99, adam_eps=1e-15, grad_max_norm=0.0, grad_max_val=0.0, distortion_loss_mult=0.005, opacity_loss_mult=0.0, eval_only_once=True, eval_save_output=True, eval_save_ray_data=False, eval_render_interval=1, eval_dataset_limit=2147483647, eval_quantize_metrics=True, eval_crop_borders=0, render_video_fps=30, render_video_crf=18, render_path_frames=120, z_variation=0.0, z_phase=0.0, render_dist_percentile=0.5, render_dist_curve_fn=<ufunc 'log'>, render_path_file=None, render_resolution=None, render_focal=None, render_camtype=None, render_spherical=False, render_save_async=True, render_spline_keyframes=None, render_spline_n_interp=30, render_spline_degree=5, render_spline_smoothness=0.03, render_spline_interpolate_exposure=False, rawnerf_mode=False, exposure_percentile=97.0, num_border_pixels_to_mask=0, apply_bayer_mask=False, autoexpose_renders=False, eval_raw_affine_cc=False, zero_glo=False, valid_weight_thresh=0.05, isosurface_threshold=20, mesh_voxels=134217728, visibility_resolution=512, mesh_radius=1.0, mesh_max_radius=10.0, std_value=0.0, compute_visibility=False, extract_visibility=True, decimate_target=-1, vertex_color=True, vertex_projection=True)
I0612 14:12:39.029906 139869331714432 logging.py:47] Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no

E0612 14:12:39.579381 139869331714432 utils.py:40] Error!                       
Traceback (most recent call last):
  File "render.py", line 172, in <module>
    app.run(main)
  File "/home/pve/.pyenv/versions/3.7.2/lib/python3.7/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/pve/.pyenv/versions/3.7.2/lib/python3.7/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "render.py", line 107, in main
    dataset = datasets.load_dataset('test', config.data_dir, config)
  File "/home/pve/Projects/zipnerf-pytorch/internal/datasets.py", line 39, in load_dataset
    return dataset_dict[config.dataset_loader](split, train_dir, config)
  File "/home/pve/Projects/zipnerf-pytorch/internal/datasets.py", line 909, in __init__
    self.images.append(self.down2(images[i], (self.heights[-1], self.widths[-1])))
IndexError: index 15 is out of bounds for axis 0 with size 15
Traceback (most recent call last):
  File "/home/pve/.pyenv/versions/3.7.2/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/pve/.pyenv/versions/3.7.2/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/pve/.pyenv/versions/3.7.2/lib/python3.7/site-packages/accelerate/commands/launch.py", line 918, in launch_command
    simple_launcher(args)
  File "/home/pve/.pyenv/versions/3.7.2/lib/python3.7/site-packages/accelerate/commands/launch.py", line 580, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/pve/.pyenv/versions/3.7.2/bin/python3.7', 'render.py', '--gin_configs=configs/multi360.gin', "--gin_bindings=Config.data_dir = 'data/chill_room_113'", "--gin_bindings=Config.exp_name = 'chill_room_113_multi360'", '--gin_bindings=Config.render_path = True', '--gin_bindings=Config.render_path_frames = 120', '--gin_bindings=Config.render_video_fps = 30', '--gin_bindings=Config.factor = 2', '--gin_bindings=Config.batch_size = 6000', '--gin_bindings=Config.render_chunk_size = 6000']' returned non-zero exit status 1.
```

**Comment by SuLvXiangXin** [comment]
@Systho Don't use multi360.gin for render，use 360.gin

**Comment by Systho** [comment]
It's working, thanks !
