### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by Mark-Bassett** [SuLvXiangXin/zipnerf-pytorch#44]
tripping up on
pip install ./gridencoder

falls over on line 195 in version.py
I changed it to this,
match = self._regex.search(str(version))
from this
match = self._regex.search(version)

still does not work, seems to return "none"

spent hours searching the web to no evail.
help appreciated, as this looks to be a very promissing implementation.

thx

**Comment by SuLvXiangXin** [comment]
@Mark-Bassett Please type your error message.

**Comment by Mark-Bassett** [comment]
Thank you for your quick response, and thanks for posting the code, it looks to produce the highest quality nerf’s I have seen to date.

(zipnerf) C:\Users\markb\zipnerf-pytorch>pip install ./gridencoder
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com<https://pypi.ngc.nvidia.com/>
Processing c:\users\markb\zipnerf-pytorch\gridencoder
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: gridencoder
  Building wheel for gridencoder (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\markb\zipnerf-pytorch\gridencoder\setup.py", line 32, in <module>
          setup(
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\torch\utils\cpp_extension.py", line 383, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
          return Version(version)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: 'None'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gridencoder
  Running setup.py clean for gridencoder
Failed to build gridencoder
ERROR: Could not build wheels for gridencoder, which is required to install pyproject.toml-based projects

(zipnerf) C:\Users\markb\zipnerf-pytorch>


I will post this error on github too.



Best

Mark

**Comment by SuLvXiangXin** [comment]
It seems that you don't have your CUDA installed? Could you check the directory `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7`

**Comment by Mark-Bassett** [comment]
Interesting,

I do have the path, but the only folder is extras

C:\ProgramData\NVIDIA GPU Computing Toolkit\v11.7\extras\visual_studio_integration\CudaProjectVsWizards

I'm assuming this is not correct, will try reinstalling and let you know

**Comment by Mark-Bassett** [comment]
I have reinstalled cuda 11.7, is this the right version? It is not the latest.

However, the same error persists.

(zipnerf) C:\Users\markb\zipnerf-pytorch>pip install ./gridencoder
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com<https://pypi.ngc.nvidia.com/>
Processing c:\users\markb\zipnerf-pytorch\gridencoder
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: gridencoder
  Building wheel for gridencoder (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\markb\zipnerf-pytorch\gridencoder\setup.py", line 32, in <module>
          setup(
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\torch\utils\cpp_extension.py", line 383, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
          return Version(version)
        File "C:\Users\markb\.conda\envs\zipnerf\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: 'None'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gridencoder
  Running setup.py clean for gridencoder
Failed to build gridencoder
ERROR: Could not build wheels for gridencoder, which is required to install pyproject.toml-based projects

(zipnerf) C:\Users\markb\zipnerf-pytorch>

**Comment by FlorentLM** [comment]
Make sure you install [CUDA 11.8](https://developer.nvidia.com/cuda-11-8-0-download-archive)

Add this to the top of the `requirements.txt` file:
```
--find-links https://download.pytorch.org/whl/torch_stable.html
```

Specify which version + build of torch further down in the `requirements.txt` file:
```
torch==2.0.1+cu118
```

Run this command in your conda environment:
```
conda env config vars set CUDA_HOME="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8"
```

Deactivate / reactivate the env for the `CUDA_HOME` variable to be set:
```
conda deactivate
conda activate zipnerf
```

And then carry on normally:
```
pip install -r requirements.txt
# etc
```

**Comment by guswhd** [comment]
@Mark-Bassett I'm encounting this issue exactly same with your error message. Still haven't solved this problem? If you have solved this problem, I would appreciate it if you could tell me how. : )

**Comment by s1eeveW** [comment]
@FlorentLM Hello, mate. Thanks for your great comment. I followed your comment to install the 'extension/cuda', but I still got some errors. 

I installed cuda 11.8 with cudnn 8.9.x.

requirements.txt:
--find-links https://download.pytorch.org/whl/torch_stable.html
numpy
torch==2.0.1+cu118
absl_py
accelerate
gin_config
imageio
imageio[ffmpeg]
matplotlib
mediapy
opencv_contrib_python
opencv_python
Pillow
trimesh
pymeshlab
xatlas
plyfile
rawpy
ninja
scipy
scikit-image
scikit-learn
tensorboard
tensorboardX
tqdm

Then, I got the error:
(zipnerf) E:\zipnerf-pytorch>pip install ./extensions/cuda
```
Processing e:\zipnerf-pytorch\extensions\cuda
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "E:\zipnerf-pytorch\extensions\cuda\setup.py", line 3, in <module>
          from torch.utils.cpp_extension import BuildExtension, CUDAExtension
        File "E:\Programming\Anaconda\envs\zipnerf\lib\site-packages\torch\utils\cpp_extension.py", line 25, in <module>
          from pkg_resources import packaging  # type: ignore[attr-defined]
      ImportError: cannot import name 'packaging' from 'pkg_resources' (E:\Programming\Anaconda\envs\zipnerf\lib\site-packages\pkg_resources\__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

If I downgrade the 'setuptools' to 69.5.1 (or other versions), the error would be:
```
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cuda_backend
  Running setup.py clean for cuda_backend
Failed to build cuda_backend
ERROR: Could not build wheels for cuda_backend, which is required to install pyproject.toml-based projects
```
So, do you also meet these errors or have any other good solutions?

Thank you.

**Comment by CaffeyChen** [comment]
Same error. Do you slove it?
