### ISSUE TITLE
AttributeError: 'GridEncoder' object has no attribute 'grid_sizes'

### ISSUE THREAD

**Issue by Ping-Kong-47** [SuLvXiangXin/zipnerf-pytorch#53]
@SuLvXiangXin 

hello,
After training starts I get this error, I'm using fox dataset from nvlabs/instant-ngp and got the same error with 360_v2/kitchen dataset.

```
2023-07-03 XX:XX:XX: Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

2023-07-03 XX:XX:XX: Checkpoint does not exist. Starting a new training run.
2023-07-03 XX:XX:XX: Number of parameters being optimized: 77622581
2023-07-03 XX:XX:XX: Begin training...
Training:   0%|                                                                              | 0/25000 [00:13<?, ?it/s]
2023-07-03 XX:XX:XX: Error!
Traceback (most recent call last):
  File "C:\zipnerf-pytorch\train.py", line 387, in <module>
    app.run(main)
  File "C:\miniconda3\envs\zipnerf\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\miniconda3\envs\zipnerf\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "C:\zipnerf-pytorch\train.py", line 166, in main
    renderings, ray_history = model(
  File "C:\miniconda3\envs\zipnerf\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\miniconda3\envs\zipnerf\lib\site-packages\accelerate\utils\operations.py", line 553, in forward
    return model_forward(*args, **kwargs)
  File "C:\miniconda3\envs\zipnerf\lib\site-packages\accelerate\utils\operations.py", line 541, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "C:\miniconda3\envs\zipnerf\lib\site-packages\torch\amp\autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "C:\zipnerf-pytorch\internal\models.py", line 208, in forward
    ray_results = mlp(
  File "C:\miniconda3\envs\zipnerf\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\zipnerf-pytorch\internal\models.py", line 491, in forward
    raw_density, x, means_contract = self.predict_density(means, stds, rand=rand, no_warp=no_warp)
  File "C:\zipnerf-pytorch\internal\models.py", line 439, in predict_density
    weights = torch.erf(1 / torch.sqrt(8 * stds[..., None] ** 2 * self.encoder.grid_sizes ** 2))
  File "C:\miniconda3\envs\zipnerf\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GridEncoder' object has no attribute 'grid_sizes'
```

**Comment by SuLvXiangXin** [comment]
Maybe your are using another version of gridencoder, you need to reinstall the gridencoder, you can find the command in readme.

**Comment by Ping-Kong-47** [comment]
@SuLvXiangXin 

I installed gridencoder with

`pip install ./gridencoder` (your repo and current commit)

and got installation error which got fixed by installing torch with cuda 11.8 and now I am Getting this error

`AttributeError: 'GridEncoder' object has no attribute 'grid_sizes'`

**Comment by SuLvXiangXin** [comment]
It's weird, I'm not sure what's going on. Maybe check the version of your python and torch?
