### ISSUE TITLE
pip install ./gridencoder doesn't work

### ISSUE THREAD

**Issue by MihirSPatil** [SuLvXiangXin/zipnerf-pytorch#77]
`Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing ./gridencoder
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: gridencoder
  Building wheel for gridencoder (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [106 lines of output]
      running bdist_wheel
      running build
      running build_ext
      /home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py:388: UserWarning: The detected CUDA version (11.5) has a minor version mismatch with the version that was used to compile PyTorch (11.7). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building '_gridencoder' extension
      creating /home/mihir/zipnerf-pytorch/gridencoder/build
      creating /home/mihir/zipnerf-pytorch/gridencoder/build/temp.linux-x86_64-cpython-39
      creating /home/mihir/zipnerf-pytorch/gridencoder/build/temp.linux-x86_64-cpython-39/home
      creating /home/mihir/zipnerf-pytorch/gridencoder/build/temp.linux-x86_64-cpython-39/home/mihir
      creating /home/mihir/zipnerf-pytorch/gridencoder/build/temp.linux-x86_64-cpython-39/home/mihir/zipnerf-pytorch
      creating /home/mihir/zipnerf-pytorch/gridencoder/build/temp.linux-x86_64-cpython-39/home/mihir/zipnerf-pytorch/gridencoder
      creating /home/mihir/zipnerf-pytorch/gridencoder/build/temp.linux-x86_64-cpython-39/home/mihir/zipnerf-pytorch/gridencoder/src
      Emitting ninja build file /home/mihir/zipnerf-pytorch/gridencoder/build/temp.linux-x86_64-cpython-39/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/2] c++ -MMD -MF /home/mihir/zipnerf-pytorch/gridencoder/build/temp.linux-x86_64-cpython-39/home/mihir/zipnerf-pytorch/gridencoder/src/bindings.o.d -pthread -B /home/mihir/miniconda3/envs/zipnerf/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/mihir/miniconda3/envs/zipnerf/include -I/home/mihir/miniconda3/envs/zipnerf/include -fPIC -O2 -isystem /home/mihir/miniconda3/envs/zipnerf/include -fPIC -I/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/include -I/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/include/TH -I/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/include/THC -I/home/mihir/miniconda3/envs/zipnerf/include/python3.9 -c -c /home/mihir/zipnerf-pytorch/gridencoder/src/bindings.cpp -o /home/mihir/zipnerf-pytorch/gridencoder/build/temp.linux-x86_64-cpython-39/home/mihir/zipnerf-pytorch/gridencoder/src/bindings.o -O3 -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_gridencoder -D_GLIBCXX_USE_CXX11_ABI=0
      [2/2] /usr/bin/nvcc  -I/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/include -I/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/include/TH -I/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/include/THC -I/home/mihir/miniconda3/envs/zipnerf/include/python3.9 -c -c /home/mihir/zipnerf-pytorch/gridencoder/src/gridencoder.cu -o /home/mihir/zipnerf-pytorch/gridencoder/build/temp.linux-x86_64-cpython-39/home/mihir/zipnerf-pytorch/gridencoder/src/gridencoder.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_gridencoder -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
      FAILED: /home/mihir/zipnerf-pytorch/gridencoder/build/temp.linux-x86_64-cpython-39/home/mihir/zipnerf-pytorch/gridencoder/src/gridencoder.o
      /usr/bin/nvcc  -I/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/include -I/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/include/TH -I/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/include/THC -I/home/mihir/miniconda3/envs/zipnerf/include/python3.9 -c -c /home/mihir/zipnerf-pytorch/gridencoder/src/gridencoder.cu -o /home/mihir/zipnerf-pytorch/gridencoder/build/temp.linux-x86_64-cpython-39/home/mihir/zipnerf-pytorch/gridencoder/src/gridencoder.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_gridencoder -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
      /home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      /home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/include/c10/core/TensorImpl.h(77): here
      
      /home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
      /home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/include/ATen/core/qualified_name.h(73): here
      
      /usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
        435 |         function(_Functor&& __f)
            |                                                                                                                                                 ^
      /usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
      /usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
        530 |         operator=(_Functor&& __f)
            |                                                                                                                                                  ^
      /usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
          subprocess.run(
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/mihir/zipnerf-pytorch/gridencoder/setup.py", line 32, in <module>
          setup(
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/mihir/miniconda3/envs/zipnerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gridencoder
  Running setup.py clean for gridencoder
Failed to build gridencoder
ERROR: Could not build wheels for gridencoder, which is required to install pyproject.toml-based projects
`

I get the above error when trying to install the repository, any help/ideas would be greatly appreciated

**Comment by AdityaDhaulakhandi** [comment]
`CXX=g++-10 pip install ./gridencoder` -- you can use another version of g++, mine worked with this
