### ISSUE TITLE
checkpoint mismatch

### ISSUE THREAD

**Issue by xiyufeng2** [SuLvXiangXin/zipnerf-pytorch#79]
when I load the trained checkpoint， there is an error：
        size mismatch for prop_mlp_0.encoder.embeddings: copying a param with shape torch.Size([6606952, 1]) from checkpoint, the shape in current model is torch.Size([6606952, 4]).
        size mismatch for prop_mlp_0.density_layer.0.weight: copying a param with shape torch.Size([64, 6]) from checkpoint, the shape in current model is torch.Size([64, 24]).
        size mismatch for prop_mlp_0.density_layer.2.weight: copying a param with shape torch.Size([1, 64]) from checkpoint, the shape in current model is torch.Size([256, 64]).
        size mismatch for prop_mlp_0.density_layer.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for prop_mlp_1.encoder.embeddings: copying a param with shape torch.Size([10801256, 1]) from checkpoint, the shape in current model is torch.Size([10801256, 4]).
        size mismatch for prop_mlp_1.density_layer.0.weight: copying a param with shape torch.Size([64, 8]) from checkpoint, the shape in current model is torch.Size([64, 32]).
        size mismatch for prop_mlp_1.density_layer.2.weight: copying a param with shape torch.Size([1, 64]) from checkpoint, the shape in current model is torch.Size([256, 64]).
        size mismatch for prop_mlp_1.density_layer.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([256]).

**Comment by lan-creator** [comment]
I have similar problem, and I set the num level of gridencoder to 1. The train is ok, but when I eval the model, the error occured:
Traceback (most recent call last):
  File "/data/Code/zipnerf-pytorch/eval.py", line 307, in <module>
    app.run(main)
  File "/data/App/anaconda3/envs/zipnerf/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/data/App/anaconda3/envs/zipnerf/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/data/Code/zipnerf-pytorch/eval.py", line 115, in main
    step = checkpoints.restore_checkpoint(config.checkpoint_dir, accelerator, logger)
  File "/data/Code/zipnerf-pytorch/internal/checkpoints.py", line 24, in restore_checkpoint
    accelerator.load_state(path)
  File "/data/App/anaconda3/envs/zipnerf/lib/python3.9/site-packages/accelerate/accelerator.py", line 2922, in load_state
    load_accelerator_state(
  File "/data/App/anaconda3/envs/zipnerf/lib/python3.9/site-packages/accelerate/checkpointing.py", line 205, in load_accelerator_state
    models[i].load_state_dict(state_dict, **load_model_func_kwargs)
  File "/data/App/anaconda3/envs/zipnerf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Model:
        size mismatch for nerf_mlp.encoder.embeddings: copying a param with shape torch.Size([4920, 8]) from checkpoint, the shape in current model is torch.Size([23967296, 8]).
        size mismatch for nerf_mlp.encoder.offsets: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([17]).
        size mismatch for nerf_mlp.encoder.idx: copying a param with shape torch.Size([4920]) from checkpoint, the shape in current model is torch.Size([23967296]).
        size mismatch for nerf_mlp.encoder.grid_sizes: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([16]).
        size mismatch for nerf_mlp.density_layer.0.weight: copying a param with shape torch.Size([64, 8]) from checkpoint, the shape in current model is torch.Size([64, 128]).
        size mismatch for prop_mlp_0.encoder.embeddings: copying a param with shape torch.Size([4920, 1]) from checkpoint, the shape in current model is torch.Size([16897552, 1]).
        size mismatch for prop_mlp_0.encoder.offsets: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([17]).
        size mismatch for prop_mlp_0.encoder.idx: copying a param with shape torch.Size([4920]) from checkpoint, the shape in current model is torch.Size([16897552]).
        size mismatch for prop_mlp_0.encoder.grid_sizes: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([16]).
        size mismatch for prop_mlp_0.density_layer.0.weight: copying a param with shape torch.Size([64, 1]) from checkpoint, the shape in current model is torch.Size([64, 16]).
        size mismatch for prop_mlp_1.encoder.embeddings: copying a param with shape torch.Size([4920, 1]) from checkpoint, the shape in current model is torch.Size([21221336, 1]).
        size mismatch for prop_mlp_1.encoder.offsets: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([17]).
        size mismatch for prop_mlp_1.encoder.idx: copying a param with shape torch.Size([4920]) from checkpoint, the shape in current model is torch.Size([21221336]).
        size mismatch for prop_mlp_1.encoder.grid_sizes: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([16]).
        size mismatch for prop_mlp_1.density_layer.0.weight: copying a param with shape torch.Size([64, 1]) from checkpoint, the shape in current model is torch.Size([64, 16]).
