### ISSUE TITLE
Nan or Inf found in input tensor

### ISSUE THREAD

**Issue by marisancans** [SuLvXiangXin/zipnerf-pytorch#8]
I'm trying to use my own data [following this](https://github.com/google-research/multinerf#using-your-own-data)

Here is the error. It looks like it happens when writing loss or some other scalar to tensorboard which is a nan.
Now the question is why is it even nan? Has COLMAP not found some links between images or something?
How to even handle such cases? 
Using colmap scripts from multineft didnt fail, but generated like 8GB of data. I have 1000 images in that case, is it too much maybe?

```
[2023-04-28 07:59:22,211] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 0
[2023-04-28 07:59:22,212] torch._dynamo.output_graph: [INFO] Step 2: done compiler function debug_wrapper
[2023-04-28 07:59:24,575] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing contract_mean_jacobi
[2023-04-28 07:59:24,633] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo done tracing contract_mean_jacobi (RETURN_VALUE)
[2023-04-28 07:59:24,637] torch._dynamo.output_graph: [INFO] Step 2: calling compiler function debug_wrapper
[2023-04-28 07:59:24,770] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 1
[2023-04-28 07:59:26,212] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 1
[2023-04-28 07:59:26,212] torch._dynamo.output_graph: [INFO] Step 2: done compiler function debug_wrapper
W0428 07:59:26.409256 140601599434880 x2num.py:14] NaN or Inf found in input tensor.
  0%|                                                                                                   | 0/25000 [00:21<?, ?it/s]
Traceback (most recent call last):
  File "/workspaces/zipnerf-pytorch/train.py", line 373, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/workspaces/zipnerf-pytorch/train.py", line 228, in main
    summary_writer.add_histogram('train_' + k, v, step)
  File "/opt/conda/lib/python3.10/site-packages/tensorboardX/writer.py", line 562, in add_histogram
    histogram(tag, values, bins, max_bins=max_bins), global_step, walltime)
  File "/opt/conda/lib/python3.10/site-packages/tensorboardX/summary.py", line 209, in histogram
    hist = make_histogram(values.astype(float), bins, max_bins)
  File "/opt/conda/lib/python3.10/site-packages/tensorboardX/summary.py", line 247, in make_histogram
    raise ValueError('The histogram is empty, please file a bug report.')
ValueError: The histogram is empty, please file a bug report.
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 923, in launch_command
    simple_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', 'train.py', '--gin_configs=configs/360.gin', "--gin_bindings=Config.data_dir = './data/office'", "--gin_bindings=Config.exp_name = '360_v2/office'", '--gin_bindings=Config.batch_size = 16384', '--gin_bindings=Config.factor = 4', '--gin_bindings=Config.render_chunk_size = 16384']' returned non-zero exit status 1.

```

**Comment by SuLvXiangXin** [comment]
Maybe you can use the nan_sum function in utils.py to debug, and see in which step there comes up a nan, so you can find a way to solve it. By the way, I find that fp16 maybe unstable , if you are using fp16, you can try to turn it out and have another try.

**Comment by marisancans** [comment]
I'm using scripts/train_360.sh script, I don't know if accelerate uses FP16 (I don't have any experience with accelerate).
I think the reason is that COLMAP was unable to find control points between some images.
