### ISSUE TITLE
fail pip install gridencoder

### ISSUE THREAD

**Issue by MbertoldiNormal** [SuLvXiangXin/zipnerf-pytorch#89]
heres te software list
Anaconda
Cuda 11.8
visual studio community 2019

> (zipnerf) C:\Users\mbertoldi\zipnerf-pytorch>pip install ./gridencoder
> Processing c:\users\mbertoldi\zipnerf-pytorch\gridencoder
>   Preparing metadata (setup.py) ... done
> Building wheels for collected packages: gridencoder
>   Building wheel for gridencoder (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [97 lines of output]
>       running bdist_wheel
>       running build
>       running build_ext
>       building '_gridencoder' extension
>       creating C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\build
>       creating C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\build\temp.win-amd64-cpython-39
>       creating C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\build\temp.win-amd64-cpython-39\Release
>       creating C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\build\temp.win-amd64-cpython-39\Release\Users
>       creating C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\build\temp.win-amd64-cpython-39\Release\Users\mbertoldi
>       creating C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\build\temp.win-amd64-cpython-39\Release\Users\mbertoldi\zipnerf-pytorch
>       creating C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\build\temp.win-amd64-cpython-39\Release\Users\mbertoldi\zipnerf-pytorch\gridencoder
>       creating C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\build\temp.win-amd64-cpython-39\Release\Users\mbertoldi\zipnerf-pytorch\gridencoder\src
>       Emitting ninja build file C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\build\temp.win-amd64-cpython-39\Release\build.ninja...
>       Compiling objects...
>       Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
>       [1/2] cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\include -IC:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\include\TH -IC:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\mbertoldi\.conda\envs\zipnerf\include -IC:\Users\mbertoldi\.conda\envs\zipnerf\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -c C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\src\bindings.cpp /FoC:\Users\mbertoldi\zipnerf-pytorch\gridencoder\build\temp.win-amd64-cpython-39\Release\Users\mbertoldi\zipnerf-pytorch\gridencoder\src\bindings.obj /O2 /std:c++17 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_gridencoder -D_GLIBCXX_USE_CXX11_ABI=0
>       FAILED: C:/Users/mbertoldi/zipnerf-pytorch/gridencoder/build/temp.win-amd64-cpython-39/Release/Users/mbertoldi/zipnerf-pytorch/gridencoder/src/bindings.obj
>       cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\include -IC:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\include\TH -IC:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\mbertoldi\.conda\envs\zipnerf\include -IC:\Users\mbertoldi\.conda\envs\zipnerf\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -c C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\src\bindings.cpp /FoC:\Users\mbertoldi\zipnerf-pytorch\gridencoder\build\temp.win-amd64-cpython-39\Release\Users\mbertoldi\zipnerf-pytorch\gridencoder\src\bindings.obj /O2 /std:c++17 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_gridencoder -D_GLIBCXX_USE_CXX11_ABI=0
>       C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\cassert(9): fatal error C1083: Cannot open include file: 'assert.h': No such file or directory
>       [2/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\build\temp.win-amd64-cpython-39\Release\Users\mbertoldi\zipnerf-pytorch\gridencoder\src\gridencoder.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\include -IC:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\include\TH -IC:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\mbertoldi\.conda\envs\zipnerf\include -IC:\Users\mbertoldi\.conda\envs\zipnerf\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -c C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\src\gridencoder.cu -o C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\build\temp.win-amd64-cpython-39\Release\Users\mbertoldi\zipnerf-pytorch\gridencoder\src\gridencoder.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_gridencoder -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
>       FAILED: C:/Users/mbertoldi/zipnerf-pytorch/gridencoder/build/temp.win-amd64-cpython-39/Release/Users/mbertoldi/zipnerf-pytorch/gridencoder/src/gridencoder.obj
>       C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\build\temp.win-amd64-cpython-39\Release\Users\mbertoldi\zipnerf-pytorch\gridencoder\src\gridencoder.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\include -IC:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\include\TH -IC:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\mbertoldi\.conda\envs\zipnerf\include -IC:\Users\mbertoldi\.conda\envs\zipnerf\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -c C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\src\gridencoder.cu -o C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\build\temp.win-amd64-cpython-39\Release\Users\mbertoldi\zipnerf-pytorch\gridencoder\src\gridencoder.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_gridencoder -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
>       cl : Command line warning D9025 : overriding '/D__CUDA_NO_HALF_OPERATORS__' with '/U__CUDA_NO_HALF_OPERATORS__'
>       cl : Command line warning D9025 : overriding '/D__CUDA_NO_HALF_CONVERSIONS__' with '/U__CUDA_NO_HALF_CONVERSIONS__'
> 
>       cl : Command line warning D9025 : overriding '/D__CUDA_NO_HALF2_OPERATORS__' with '/U__CUDA_NO_HALF2_OPERATORS__'
> 
>       gridencoder.cu
> 
>       **C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\driver_types.h(82): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory**
> 
>       gridencoder.cu
> 
>       ninja: build stopped: subcommand failed.
>       Traceback (most recent call last):
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\utils\cpp_extension.py", line 1893, in _run_ninja_build
>           subprocess.run(
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\subprocess.py", line 528, in run
>           raise CalledProcessError(retcode, process.args,
>       subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
>       The above exception was the direct cause of the following exception:
> 
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\mbertoldi\zipnerf-pytorch\gridencoder\setup.py", line 32, in <module>
>           setup(
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\__init__.py", line 107, in setup
>           return distutils.core.setup(**attrs)
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
>           return run_commands(dist)
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
>           dist.run_commands()
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
>           self.run_command(cmd)
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\dist.py", line 1234, in run_command
>           super().run_command(command)
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\wheel\bdist_wheel.py", line 364, in run
>           self.run_command("build")
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
>           self.distribution.run_command(command)
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\dist.py", line 1234, in run_command
>           super().run_command(command)
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
>           self.run_command(cmd_name)
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
>           self.distribution.run_command(command)
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\dist.py", line 1234, in run_command
>           super().run_command(command)
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
>           _build_ext.run(self)
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
>           self.build_extensions()
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\utils\cpp_extension.py", line 843, in build_extensions
>           build_ext.build_extensions(self)
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
>           self._build_extensions_serial()
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
>           self.build_extension(ext)
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
>           _build_ext.build_extension(self, ext)
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
>           objects = self.compiler.compile(
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\utils\cpp_extension.py", line 815, in win_wrap_ninja_compile
>           _write_ninja_file_and_compile_objects(
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\utils\cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
>           _run_ninja_build(
>         File "C:\Users\mbertoldi\.conda\envs\zipnerf\lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build
>           raise RuntimeError(message) from e
>       RuntimeError: Error compiling objects for extension
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for gridencoder
>   Running setup.py clean for gridencoder
> Failed to build gridencoder
> ERROR: Could not build wheels for gridencoder, which is required to install pyproject.toml-based projects

looks like im missing stddef.h ?

**Comment by cannedpeanutbutter** [comment]
i built it on ubuntu 20. 
my cuda version is 11.3 and torch=2.1.0, then i got a Runtime Error: the detected CUDA version(11.3) mismatches the version that was used to compile Pytorch(12.1). Please make sure to use the same CUDA versions. 
then i change my pytorch version to match cuda11.3, it dose work.
you may check your software versions.

**Comment by datasciritwik** [comment]
Similar error!! plz help


Processing ./gridencoder
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: gridencoder
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for gridencoder (setup.py) ... error
  ERROR: Failed building wheel for gridencoder
  Running setup.py clean for gridencoder
Failed to build gridencoder
ERROR: Could not build wheels for gridencoder, which is required to install pyproject.toml-based projects

**Comment by hongju-jeong** [comment]
I recommend to using torch==2.0.0
Modify requirements.txt torch ->torch==2.0.0

**Comment by gaurav00700** [comment]
I was able to build cuda extensions by adding environment variable for cuda artchitecture in front of build command. 
First install torch and cuda-toolkit 
Then run build command
```
pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
conda install -c "nvidia/label/cuda-11.8.0" cuda-toolkit
TORCH_CUDA_ARCH_LIST=6.0 pip install ./extensions/cuda
```

**Comment by YuQiao0303** [comment]
I solve the same issue from prolificdreamer:


modify gridencoder/setup.py, replace all "c++14" into "c++17":
```python
nvcc_flags = [
    # '-O3', '-std=c++14',
    '-O3', '-std=c++17',
    '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_HALF2_OPERATORS__',
]

if os.name == "posix":
    # c_flags = ['-O3', '-std=c++14']
    c_flags = ['-O3', '-std=c++17']
elif os.name == "nt":
    c_flags = ['/O2', '/std:c++17']
```
